2023-10-09 20:31:11,914 INFO    StreamThr :22733 [internal.py:wandb_internal():86] W&B internal server running at pid: 22733, started at: 2023-10-09 20:31:11.913592
2023-10-09 20:31:11,916 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status
2023-10-09 20:31:11,925 INFO    WriterThread:22733 [datastore.py:open_for_write():85] open: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/run-oxxnz7ac.wandb
2023-10-09 20:31:11,926 DEBUG   SenderThread:22733 [sender.py:send():380] send: header
2023-10-09 20:31:11,971 DEBUG   SenderThread:22733 [sender.py:send():380] send: run
2023-10-09 20:31:12,884 INFO    SenderThread:22733 [dir_watcher.py:__init__():211] watching files in: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files
2023-10-09 20:31:12,884 INFO    SenderThread:22733 [sender.py:_start_run_threads():1122] run started: oxxnz7ac with start time 1696863671.914308
2023-10-09 20:31:12,900 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: check_version
2023-10-09 20:31:12,900 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: check_version
2023-10-09 20:31:13,245 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: run_start
2023-10-09 20:31:13,253 DEBUG   HandlerThread:22733 [system_info.py:__init__():32] System info init
2023-10-09 20:31:13,253 DEBUG   HandlerThread:22733 [system_info.py:__init__():47] System info init done
2023-10-09 20:31:13,253 INFO    HandlerThread:22733 [system_monitor.py:start():181] Starting system monitor
2023-10-09 20:31:13,253 INFO    SystemMonitor:22733 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-10-09 20:31:13,253 INFO    HandlerThread:22733 [system_monitor.py:probe():201] Collecting system info
2023-10-09 20:31:13,254 INFO    SystemMonitor:22733 [interfaces.py:start():190] Started cpu monitoring
2023-10-09 20:31:13,254 DEBUG   HandlerThread:22733 [system_info.py:probe():196] Probing system
2023-10-09 20:31:13,254 INFO    SystemMonitor:22733 [interfaces.py:start():190] Started disk monitoring
2023-10-09 20:31:13,255 INFO    SystemMonitor:22733 [interfaces.py:start():190] Started gpuapple monitoring
2023-10-09 20:31:13,258 INFO    SystemMonitor:22733 [interfaces.py:start():190] Started memory monitoring
2023-10-09 20:31:13,261 INFO    SystemMonitor:22733 [interfaces.py:start():190] Started network monitoring
2023-10-09 20:31:13,266 DEBUG   HandlerThread:22733 [system_info.py:_probe_git():181] Probing git
2023-10-09 20:31:13,300 DEBUG   HandlerThread:22733 [system_info.py:_probe_git():189] Probing git done
2023-10-09 20:31:13,300 DEBUG   HandlerThread:22733 [system_info.py:probe():244] Probing system done
2023-10-09 20:31:13,300 DEBUG   HandlerThread:22733 [system_monitor.py:probe():210] {'os': 'macOS-13.4.1-arm64-arm-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-10-09T15:01:13.254614', 'startedAt': '2023-10-09T15:01:11.902822', 'docker': None, 'cuda': None, 'args': ('--track', '1', '--description', 'Trial2'), 'state': 'running', 'program': '/Users/stav.42/RL_Library/cartpole/ppo/tparallel.py', 'codePathLocal': 'tparallel.py', 'codePath': 'cartpole/ppo/tparallel.py', 'git': {'remote': 'https://github.com/Stav42/RL_Library.git', 'commit': 'e5a95f7668542412b98f1859d25e50b0f64aaa4a'}, 'email': 'vaditya@iitk.ac.in', 'root': '/Users/stav.42/RL_Library', 'host': 'Adityas-MacBook-Pro.local', 'username': 'stav.42', 'executable': '/Users/stav.42/miniconda3/envs/pytorch_rl/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 123.85487365722656}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2023-10-09 20:31:13,300 INFO    HandlerThread:22733 [system_monitor.py:probe():211] Finished collecting system info
2023-10-09 20:31:13,300 INFO    HandlerThread:22733 [system_monitor.py:probe():214] Publishing system info
2023-10-09 20:31:13,300 DEBUG   HandlerThread:22733 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-10-09 20:31:13,301 DEBUG   HandlerThread:22733 [system_info.py:_save_pip():68] Saving pip packages done
2023-10-09 20:31:13,301 DEBUG   HandlerThread:22733 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-10-09 20:31:13,891 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/requirements.txt
2023-10-09 20:31:13,892 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/conda-environment.yaml
2023-10-09 20:31:16,873 DEBUG   HandlerThread:22733 [system_info.py:_save_conda():87] Saving conda packages done
2023-10-09 20:31:16,873 DEBUG   HandlerThread:22733 [system_info.py:_save_code():90] Saving code
2023-10-09 20:31:16,890 DEBUG   HandlerThread:22733 [system_info.py:_save_code():111] Saving code done
2023-10-09 20:31:16,891 DEBUG   HandlerThread:22733 [system_info.py:_save_patches():128] Saving git patches
2023-10-09 20:31:16,902 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/conda-environment.yaml
2023-10-09 20:31:16,902 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/code/cartpole/ppo/tparallel.py
2023-10-09 20:31:16,902 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/code
2023-10-09 20:31:16,902 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/code/cartpole
2023-10-09 20:31:16,902 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/code/cartpole/ppo
2023-10-09 20:31:16,989 DEBUG   HandlerThread:22733 [system_info.py:_save_patches():170] Saving git patches done
2023-10-09 20:31:16,990 INFO    HandlerThread:22733 [system_monitor.py:probe():216] Finished publishing system info
2023-10-09 20:31:16,996 DEBUG   SenderThread:22733 [sender.py:send():380] send: files
2023-10-09 20:31:16,996 INFO    SenderThread:22733 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-10-09 20:31:16,996 INFO    SenderThread:22733 [sender.py:_save_file():1378] saving file code/cartpole/ppo/tparallel.py with policy now
2023-10-09 20:31:16,997 INFO    SenderThread:22733 [sender.py:_save_file():1378] saving file diff.patch with policy now
2023-10-09 20:31:16,997 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:17,002 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:31:17,002 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:31:17,003 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:31:17,444 DEBUG   SenderThread:22733 [sender.py:send():380] send: telemetry
2023-10-09 20:31:17,907 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/output.log
2023-10-09 20:31:17,908 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/wandb-metadata.json
2023-10-09 20:31:17,908 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/diff.patch
2023-10-09 20:31:18,234 INFO    wandb-upload_0:22733 [upload_job.py:push():131] Uploaded file /var/folders/f5/tz3zrky52t382vsv5zf3y6j00000gn/T/tmpyqed6uqawandb/5p0on1g5-wandb-metadata.json
2023-10-09 20:31:18,393 INFO    wandb-upload_2:22733 [upload_job.py:push():131] Uploaded file /var/folders/f5/tz3zrky52t382vsv5zf3y6j00000gn/T/tmpyqed6uqawandb/dc6u4pl9-diff.patch
2023-10-09 20:31:18,409 INFO    wandb-upload_1:22733 [upload_job.py:push():131] Uploaded file /var/folders/f5/tz3zrky52t382vsv5zf3y6j00000gn/T/tmpyqed6uqawandb/6g9ehen5-code/cartpole/ppo/tparallel.py
2023-10-09 20:31:19,921 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/output.log
2023-10-09 20:31:22,470 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:27,496 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:32,007 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:31:32,007 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:31:32,007 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:31:32,549 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:37,571 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:42,602 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:44,041 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/config.yaml
2023-10-09 20:31:47,012 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:31:47,012 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:31:47,013 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:31:48,397 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:53,418 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:31:58,444 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:02,016 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:32:02,016 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:32:02,016 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:32:03,454 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:08,480 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:13,267 DEBUG   SystemMonitor:22733 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-10-09 20:32:13,268 DEBUG   SenderThread:22733 [sender.py:send():380] send: telemetry
2023-10-09 20:32:13,268 DEBUG   SenderThread:22733 [sender.py:send():380] send: stats
2023-10-09 20:32:14,277 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:15,202 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/config.yaml
2023-10-09 20:32:17,021 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:32:17,021 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:32:17,022 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:32:20,516 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:25,538 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:30,561 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:32,025 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:32:32,025 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:32:32,026 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:32:35,565 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:40,591 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:43,274 DEBUG   SenderThread:22733 [sender.py:send():380] send: stats
2023-10-09 20:32:46,289 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:47,030 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:32:47,033 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: stop_status
2023-10-09 20:32:47,055 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: stop_status
2023-10-09 20:32:51,431 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:32:56,457 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:33:00,473 DEBUG   SenderThread:22733 [sender.py:send():380] send: exit
2023-10-09 20:33:00,474 INFO    SenderThread:22733 [sender.py:send_exit():585] handling exit code: 255
2023-10-09 20:33:00,474 INFO    SenderThread:22733 [sender.py:send_exit():587] handling runtime: 107
2023-10-09 20:33:00,475 INFO    SenderThread:22733 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-10-09 20:33:00,476 INFO    SenderThread:22733 [sender.py:send_exit():593] send defer
2023-10-09 20:33:00,476 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,476 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 0
2023-10-09 20:33:00,476 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,476 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 0
2023-10-09 20:33:00,476 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 1
2023-10-09 20:33:00,476 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,476 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 1
2023-10-09 20:33:00,476 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,476 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 1
2023-10-09 20:33:00,476 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 2
2023-10-09 20:33:00,476 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,476 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 2
2023-10-09 20:33:00,477 INFO    HandlerThread:22733 [system_monitor.py:finish():190] Stopping system monitor
2023-10-09 20:33:00,477 DEBUG   SystemMonitor:22733 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-10-09 20:33:00,477 INFO    HandlerThread:22733 [interfaces.py:finish():202] Joined cpu monitor
2023-10-09 20:33:00,477 DEBUG   SystemMonitor:22733 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-10-09 20:33:00,477 INFO    HandlerThread:22733 [interfaces.py:finish():202] Joined disk monitor
2023-10-09 20:33:00,478 INFO    HandlerThread:22733 [interfaces.py:finish():202] Joined gpuapple monitor
2023-10-09 20:33:00,478 INFO    HandlerThread:22733 [interfaces.py:finish():202] Joined memory monitor
2023-10-09 20:33:00,478 INFO    HandlerThread:22733 [interfaces.py:finish():202] Joined network monitor
2023-10-09 20:33:00,479 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 2
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 3
2023-10-09 20:33:00,479 DEBUG   SenderThread:22733 [sender.py:send():380] send: stats
2023-10-09 20:33:00,479 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,479 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 3
2023-10-09 20:33:00,479 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 3
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 4
2023-10-09 20:33:00,479 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,479 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 4
2023-10-09 20:33:00,479 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 4
2023-10-09 20:33:00,479 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 5
2023-10-09 20:33:00,479 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,479 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 5
2023-10-09 20:33:00,480 DEBUG   SenderThread:22733 [sender.py:send():380] send: summary
2023-10-09 20:33:00,480 INFO    SenderThread:22733 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-10-09 20:33:00,480 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,480 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 5
2023-10-09 20:33:00,480 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 6
2023-10-09 20:33:00,480 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,480 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 6
2023-10-09 20:33:00,480 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,480 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 6
2023-10-09 20:33:00,480 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 7
2023-10-09 20:33:00,480 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:33:00,480 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:00,480 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 7
2023-10-09 20:33:00,481 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:00,481 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 7
2023-10-09 20:33:01,435 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/wandb-summary.json
2023-10-09 20:33:01,479 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: poll_exit
2023-10-09 20:33:02,480 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 8
2023-10-09 20:33:02,481 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: poll_exit
2023-10-09 20:33:02,481 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:02,481 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 8
2023-10-09 20:33:02,482 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:02,482 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 8
2023-10-09 20:33:02,482 INFO    SenderThread:22733 [job_builder.py:build():281] Attempting to build job artifact
2023-10-09 20:33:02,484 INFO    SenderThread:22733 [job_builder.py:_get_source_type():393] is repo sourced job
2023-10-09 20:33:02,487 INFO    SenderThread:22733 [job_builder.py:build():369] adding wandb-job metadata file
2023-10-09 20:33:02,493 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 9
2023-10-09 20:33:02,493 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:02,493 DEBUG   SenderThread:22733 [sender.py:send():380] send: artifact
2023-10-09 20:33:02,493 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 9
2023-10-09 20:33:03,444 INFO    Thread-12 :22733 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/output.log
2023-10-09 20:33:05,324 INFO    wandb-upload_0:22733 [upload_job.py:push():86] Skipped uploading /Users/stav.42/Library/Application Support/wandb/artifacts/staging/tmpxw_79wk2
2023-10-09 20:33:05,324 INFO    wandb-upload_2:22733 [upload_job.py:push():86] Skipped uploading /Users/stav.42/Library/Application Support/wandb/artifacts/staging/tmpl1fm55y6
2023-10-09 20:33:06,043 INFO    wandb-upload_1:22733 [upload_job.py:push():89] Uploaded file /Users/stav.42/Library/Application Support/wandb/artifacts/staging/tmpp2eb5gik
2023-10-09 20:33:06,497 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: keepalive
2023-10-09 20:33:08,237 ERROR   SenderThread:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,237 ERROR   SenderThread:22733 [internal_api.py:execute():370] {"errors":[{"message":"failed to find run Prototype/oxxnz7ac","path":["useArtifact"]}],"data":{"useArtifact":null}}
2023-10-09 20:33:08,238 ERROR   SenderThread:22733 [sender.py:send_artifact():1458] send_artifact: failed for artifact "job/job-https___github.com_Stav42_RL_Library.git_cartpole_ppo_tparallel.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:08,238 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:08,238 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: status_report
2023-10-09 20:33:08,238 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 9
2023-10-09 20:33:08,239 INFO    SenderThread:22733 [dir_watcher.py:finish():358] shutting down directory watcher
2023-10-09 20:33:08,466 INFO    SenderThread:22733 [dir_watcher.py:finish():388] scan: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files
2023-10-09 20:33:08,467 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/diff.patch diff.patch
2023-10-09 20:33:08,467 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/requirements.txt requirements.txt
2023-10-09 20:33:08,467 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/output.log output.log
2023-10-09 20:33:08,472 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/config.yaml config.yaml
2023-10-09 20:33:08,477 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/wandb-summary.json wandb-summary.json
2023-10-09 20:33:08,481 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/conda-environment.yaml conda-environment.yaml
2023-10-09 20:33:08,484 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/wandb-metadata.json wandb-metadata.json
2023-10-09 20:33:08,489 INFO    SenderThread:22733 [dir_watcher.py:finish():402] scan save: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/code/cartpole/ppo/tparallel.py code/cartpole/ppo/tparallel.py
2023-10-09 20:33:08,489 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 10
2023-10-09 20:33:08,489 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:08,490 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 10
2023-10-09 20:33:08,490 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:08,490 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 10
2023-10-09 20:33:08,490 INFO    SenderThread:22733 [file_pusher.py:finish():175] shutting down file pusher
2023-10-09 20:33:08,817 ERROR   wandb-upload_1:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,818 ERROR   wandb-upload_3:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,818 ERROR   wandb-upload_1:22733 [internal_api.py:execute():370] {"errors":[{"message":"run Prototype/oxxnz7ac not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-09 20:33:08,818 ERROR   wandb-upload_3:22733 [internal_api.py:execute():370] {"errors":[{"message":"run Prototype/oxxnz7ac not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-09 20:33:08,818 ERROR   Thread-11 :22733 [step_upload.py:_handle_event():200] Failed to upload file: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/output.log
Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:08,822 ERROR   wandb-upload_2:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,827 ERROR   Thread-11 :22733 [step_upload.py:_handle_event():200] Failed to upload file: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/wandb-summary.json
Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:08,828 ERROR   wandb-upload_2:22733 [internal_api.py:execute():370] {"errors":[{"message":"run Prototype/oxxnz7ac not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-09 20:33:08,828 ERROR   Thread-11 :22733 [step_upload.py:_handle_event():200] Failed to upload file: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/config.yaml
Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:08,829 ERROR   wandb-upload_0:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,829 ERROR   wandb-upload_0:22733 [internal_api.py:execute():370] {"errors":[{"message":"run Prototype/oxxnz7ac not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-09 20:33:08,829 ERROR   Thread-11 :22733 [step_upload.py:_handle_event():200] Failed to upload file: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/requirements.txt
Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:08,866 ERROR   wandb-upload_4:22733 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-09 20:33:08,866 ERROR   wandb-upload_4:22733 [internal_api.py:execute():370] {"errors":[{"message":"run Prototype/oxxnz7ac not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-09 20:33:08,866 ERROR   Thread-11 :22733 [step_upload.py:_handle_event():200] Failed to upload file: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/files/conda-environment.yaml
Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/stav.42/miniconda3/envs/pytorch_rl/lib/python3.9/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-09 20:33:09,072 INFO    Thread-11 :22733 [sender.py:transition_state():613] send defer: 11
2023-10-09 20:33:09,073 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:09,073 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 11
2023-10-09 20:33:09,074 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:09,074 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 11
2023-10-09 20:33:09,074 INFO    SenderThread:22733 [file_pusher.py:join():181] waiting for file pusher
2023-10-09 20:33:09,074 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 12
2023-10-09 20:33:09,074 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:09,074 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 12
2023-10-09 20:33:09,075 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:09,075 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 12
2023-10-09 20:33:09,075 INFO    SenderThread:22733 [file_stream.py:finish():595] file stream finish called
2023-10-09 20:33:09,387 ERROR   FileStreamThread:22733 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/vaditya/Prototype/oxxnz7ac/file_stream
NoneType: None
2023-10-09 20:33:10,084 INFO    SenderThread:22733 [file_stream.py:finish():599] file stream finish is done
2023-10-09 20:33:10,084 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 13
2023-10-09 20:33:10,085 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:10,085 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 13
2023-10-09 20:33:10,085 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:10,086 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 13
2023-10-09 20:33:10,086 INFO    SenderThread:22733 [sender.py:transition_state():613] send defer: 14
2023-10-09 20:33:10,087 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: defer
2023-10-09 20:33:10,087 DEBUG   SenderThread:22733 [sender.py:send():380] send: final
2023-10-09 20:33:10,087 INFO    HandlerThread:22733 [handler.py:handle_request_defer():170] handle defer: 14
2023-10-09 20:33:10,087 DEBUG   SenderThread:22733 [sender.py:send():380] send: footer
2023-10-09 20:33:10,088 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: defer
2023-10-09 20:33:10,088 INFO    SenderThread:22733 [sender.py:send_request_defer():609] handle sender defer: 14
2023-10-09 20:33:10,089 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: poll_exit
2023-10-09 20:33:10,089 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: server_info
2023-10-09 20:33:10,090 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: poll_exit
2023-10-09 20:33:10,090 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: get_summary
2023-10-09 20:33:10,091 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: server_info
2023-10-09 20:33:10,091 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: sampled_history
2023-10-09 20:33:10,095 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: internal_messages
2023-10-09 20:33:10,096 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: job_info
2023-10-09 20:33:10,442 DEBUG   SenderThread:22733 [sender.py:send_request():407] send_request: job_info
2023-10-09 20:33:10,443 INFO    MainThread:22733 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-09 20:33:10,443 INFO    MainThread:22733 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-09 20:33:10,444 INFO    MainThread:22733 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-09 20:33:10,445 DEBUG   HandlerThread:22733 [handler.py:handle_request():144] handle_request: shutdown
2023-10-09 20:33:10,445 INFO    HandlerThread:22733 [handler.py:finish():844] shutting down handler
2023-10-09 20:33:11,098 INFO    WriterThread:22733 [datastore.py:close():294] close: /Users/stav.42/RL_Library/cartpole/ppo/wandb/run-20231009_203111-oxxnz7ac/run-oxxnz7ac.wandb
2023-10-09 20:33:11,448 INFO    SenderThread:22733 [sender.py:finish():1534] shutting down sender
2023-10-09 20:33:11,449 INFO    SenderThread:22733 [file_pusher.py:finish():175] shutting down file pusher
2023-10-09 20:33:11,449 INFO    SenderThread:22733 [file_pusher.py:join():181] waiting for file pusher
